### ISSUE TITLE
about the pretrained model

### ISSUE THREAD

**Issue by shangshang98** [blindwatch/IINet#2]
Hello, thanks for your excellent work! 
Where can I find the pth model you pretrained such as sceneflow.pth?

**Comment by blindwatch** [comment]
Thanks for your concern. Sceneflow checkpoint can be found here [https://drive.google.com/file/d/1Jnq2vpmldAmzwUxoM83OWU87pDIYFGjs/view](url).
Spring checkpoint can be found here [https://drive.google.com/file/d/1VImTxmBh5SgDQJQ32S0XSvajKh5Jx8UF/view](url). The hyperlinks are also included in the README file. Though the checkpoint is named as '.tar', it is the same as '.pth'. You can directly load it with 'torch.load()'.

**Comment by shangshang98** [comment]
Thanks for your answer, my problem is solved！
